spring:
  application:
    name: client-user
  redis:
    database: 2
    host: localhost
    port: 6379
    # password: 1qaz@WSX
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
server:
  port: 6102
  servlet:
    context-path: /client-user

security:
  oauth2:
    client:
      #client-id、client-secret 要和认证服务中的配置一致，如果是使用 inMemory 还是 jdbc 方式。
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:6002/oauth/authorize
      access-token-uri: http://localhost:6002/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:6002/oauth/token_key
        key-value: dev

