spring:
  application:
    name: admin-client-sba
  boot:
    admin:
      client:
        url: http://localhost:12400
        username: 'admin'
        password: 'admin'


server:
  port: 12500


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    health-check-url: /actuator/health
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
