spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: admin

server:
  port: 12400

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
