spring:
  application:
    name: turbine
server:
  port: 11500

management:
  port: 11501

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/

turbine:
  # 参数指定了需要收集监控信息的服务名
  app-config: hystrix

  # 参数指定了集群名称为 default，当我们服务数量非常多的时候，可以启动多个 Turbine 服务来构建不同的聚合集群
  cluster-name-expression: new String("default")

  # 参数设置为 true，可以让同一主机上的服务通过主机名与端口号的组合来进行区分，
  # 默认情况下会以 host 来区分不同的服务，这会使得在本地调试的时候，本机上的不同服务聚合成一个服务来统计。
  combine-host-port: true


