spring:
  application:
    name: eureka-producer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
  instance:
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 20
    # Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，
    #超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
#    ip-address: ${spring.cloud.client.ip-address}:${server.port}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

server:
  port: 11000
