server:
  port: 13200


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
spring:
  application:
    name: security-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_auth?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 1800000
      max-lifetime: 1765000
      maximum-pool-size: 2
      minimum-idle: 1
      auto-commit: true


security:
  oauth2:
    client:
#      client-id: test
#      client-secret: test123
#      registered-redirect-uri: http://127.0.0.1:11000/index
    resource:
      user-info-uri: /current
      token-info-uri: /oauth/check_token
