spring:
  application:
    name: auth-jwt-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_auth?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
  redis:
    database: 2
    host: 47.108.94.141
    port: 6379
    password: BZ0963azs
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 1000ms

server:
  port: 6002



management:
  endpoint:
    health:
      enabled: true

logging:
  file:
    path: /yuelai-cloud-java
  level:
    root: DEBUG
    service: DEBUG
    repository: DEBUG
    org:
      springframework:
        boot:
          autoconfigure: ERROR